import express from "express";
import userRouter from "./user.route.js";
import productRouter from "./product.route.js";
import bannerRouter from "./banner.route.js";
import authRouter from "./auth.route.js";
import categoryPostRouter from "./categoryPost.routes.js";
import postRouter from "./post.route.js";
import categoryRouter from "./category.route.js";
import couponRouter from "./coupon.routes.js";
import paymentRouter from "./payment.route.js";
import paymentSyncRouter from "./paymentSync.route.js";
import orderRouter from "./order.route.js";
import dashboardRouter from "./dashboard.routes.js";
import cartRouter from "./cart.route.js";
import variantRouter from "./variant.route.js";
import favoriteRouter from "./favorite.route.js";
import reviewRouter from "./review.route.js";
import addressRouter from "./address.route.js";
import optionRouter from "./option.route.js";
import ghnRouter from "./ghn.route.js";
import membershipTierRouter from "./membershipTier.route.js";
const router = express.Router();
router.use("/users", userRouter);
router.use("/products", productRouter);
router.use("/banners", bannerRouter);
router.use("/auth", authRouter);
router.use("/posts", postRouter);
router.use("/carts", cartRouter);
router.use("/categoryPost", categoryPostRouter);
router.use("/categories", categoryRouter);
router.use("/coupons", couponRouter);
router.use("/payments", paymentRouter);
router.use("/payment-sync", paymentSyncRouter);
router.use("/orders", orderRouter);
router.use("/dashboard", dashboardRouter);
router.use("/variants", variantRouter);
router.use("/favorites", favoriteRouter);
router.use("/reviews", reviewRouter);
router.use("/addresses", addressRouter);
router.use("/options", optionRouter);
router.use("/ghn", ghnRouter);
router.use("/membershipTier", membershipTierRouter);
export default router;
